### ISSUE TITLE
Compilation fails for some versions of clang 

### ISSUE THREAD

**Issue by jgsogo** [conan-community/conan-pistache#2]
Working with _all_ Linux and with clang 6.0... but for other versions I get:

```
[100%] Linking CXX executable bin/example
/home/conan/.conan/data/pistache/d5608a1/conan/testing/package/9c61ecc4adefec0b4fdedb76ed396e1e069fc576/lib/libpistache.so: undefined reference to `__atomic_fetch_add_8'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Why?

![image](https://user-images.githubusercontent.com/1406456/45290518-1b6bcb00-b4f0-11e8-9811-b26c1d46eafc.png)

**Comment by danimtb** [comment]
Maybe you have to link to libatomic? No idea, just googled it and found this: https://github.com/jackaudio/jack1/issues/67

**Comment by jgsogo** [comment]
Adding ``-latomic`` it works... may add it conditionally to just the jobs that were failing, or leave it for them all. Now it is for all.
